### PR TITLE
Jst/mem leak

### PR DESCRIPTION
**Pull request by atsju**

### CODE REVIEW

**Comment by atsju** [comment]
@gr5 this should build the merge commit that we will get. you can start testing on this build output I think. Then you can release with less tests. You can also force rebuild in Dales repo (I have no access right) and check that it takes the newest master commit for the merge commit built (everything is in generated file name).

**Comment by atsju** [comment]
@gr5 this is on my fork. Do not mix up with the other PR

**Comment by gr5** [comment]
Why would I test on your repository when I already have all the changes for 7.0 (except release notes) in master on Dale's repository?  I'd much rather test on Dale's.  Then I'll send you release notes in an email and you can create the release PR.  I'll approve it and merge it and tag master to start release build.

**Comment by atsju** [comment]
This was yesterday. Before you had the necessary things merged together. 
Of course, ignore this and use the official master.

**Comment by gr5** [comment]
Oh!  Right.  lol.  I forgot you offerred that option yesterday.  yes.   Well I didn't reply but intended to wait for Dale to approve.  No rush.  And I didn't have to wait long.  I have other things to do in life!   Just like you.

Thanks again for helping out with all this.  I have things going on this morning but hope to start testing around noon and should be done by 1pm (I assume around your dinner time as you are 6 hours later) and then I'll write up and send you the release notes.  So you might still be up when I finish.  We'll see how many interruptions happen.  I'm also making XYZ stage kits for interferometers today.

**Comment by atsju** [comment]
> I have other things to do in life! Just like you.

Of course, no pressure ! I'm never expecting reviews or anything done same day or even same week. I just have some free time at the moment.

**Pull request merged**
